# Generated by Django 5.2.6 on 2026-09-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0002_phrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrase",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
