# Generated by Django 5.2.6 on 2026-09-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_phrase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='order',
        ),
    ]
