# Generated by Django 5.2.6 on 2026-09-06 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0005_alter_phrase_options_remove_phrase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='scenes.scene'),
        ),
    ]
