# Generated by Django 5.2.6 on 2026-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0007_scene_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='npc_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='display_order',
            field=models.IntegerField(),
        ),
    ]
