# Generated by Django 5.2.6 on 2026-09-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0008_phrase_npc_line_alter_phrase_display_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="phrase",
            name="unique_scene_japanese_text",
        ),
        migrations.RenameField(
            model_name="phrase",
            old_name="npc_line",
            new_name="npc_en",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="english_text",
        ),
        migrations.RemoveField(
            model_name="phrase",
            name="japanese_text",
        ),
        migrations.AddField(
            model_name="phrase",
            name="staff_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="staff_jp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="turn_order",
            field=models.CharField(default="staff_first", max_length=20),
        ),
        migrations.AddConstraint(
            model_name="phrase",
            constraint=models.UniqueConstraint(
                fields=("scene", "display_order"), name="unique_scene_display_order"
            ),
        ),
    ]
