# Generated by Django 5.2.6 on 2026-09-21 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0009_remove_phrase_unique_scene_japanese_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.TextField(blank=True, verbose_name="ユーザーの入力テキスト"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="正誤判定"),
                ),
                (
                    "feedback_comment",
                    models.TextField(blank=True, verbose_name="AIフィードバック"),
                ),
                (
                    "native_suggestions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ネイティブ言い換え候補"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="練習日時"),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_histories",
                        to="scenes.scene",
                        verbose_name="シーン",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "会話履歴",
                "verbose_name_plural": "会話履歴一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
