# Generated by Django 5.2.6 on 2026-09-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
    ]
